import os
import glob
import pandas as pd
from flask import Blueprint, render_template, request, send_from_directory
from rapidfuzz import process, fuzz

from db import get_connection

medicine_bp = Blueprint('medicine', __name__, url_prefix='/medicine')

RESULTS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'Diagramatic Results')


# ---------- Load medicines once, at import time ----------

def _load_medicines():
    conn = get_connection()
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT id, name, price, is_discontinued, manufacturer_name,
                       type, pack_size_label, short_composition1, short_composition2
                FROM medicines
                """
            )
            rows = cur.fetchall()
    finally:
        conn.close()

    df = pd.DataFrame(rows)
    df['price'] = pd.to_numeric(df['price'], errors='coerce')
    df['short_composition1'] = df['short_composition1'].fillna('')
    df['short_composition2'] = df['short_composition2'].fillna('')
    df['composition_key'] = df.apply(
        lambda r: ' + '.join(sorted(filter(None, [r['short_composition1'].strip(),
                                                    r['short_composition2'].strip()]))),
        axis=1
    )
    return df


medicines_df = _load_medicines()
ALL_NAMES = medicines_df['name'].dropna().unique().tolist()


def find_substitutes(row, exclude_discontinued=True):
    key = row['composition_key']
    if not key:
        return pd.DataFrame()

    subs = medicines_df[(medicines_df['composition_key'] == key) & (medicines_df['id'] != row['id'])]
    if exclude_discontinued:
        subs = subs[~subs['is_discontinued'].astype(bool)]

    subs = subs.copy()
    subs['savings'] = row['price'] - subs['price']
    return subs.sort_values('price', ascending=True)


# ---------- Search page ----------

@medicine_bp.route('/', methods=['GET'])
def search():
    query = request.args.get('q', '').strip()
    results = []

    if query:
        matches = process.extract(query, ALL_NAMES, scorer=fuzz.WRatio, limit=15, score_cutoff=60)
        matched_names = [m[0] for m in matches]

        matched_df = medicines_df[medicines_df['name'].isin(matched_names)].drop_duplicates(subset='name')
        results = matched_df.to_dict('records')

    return render_template('medicine_search.html', query=query, results=results)


# ---------- Medicine detail + substitutes ----------

@medicine_bp.route('/view/<int:medicine_id>', methods=['GET'])
def view(medicine_id):
    candidates = medicines_df[medicines_df['id'] == medicine_id]
    if candidates.empty:
        return render_template('medicine_view.html', error='Medicine not found.', medicine=None, substitutes=[])

    medicine = candidates.iloc[0]
    substitutes_df = find_substitutes(medicine)
    substitutes = substitutes_df.to_dict('records')

    return render_template(
        'medicine_view.html',
        error=None,
        medicine=medicine.to_dict(),
        substitutes=substitutes
    )


# ---------- Insights dashboard (charts generated by main.py) ----------

def get_latest_results():
    """Finds the most recent timestamped run folder inside Diagramatic Results and lists its images."""
    if not os.path.isdir(RESULTS_DIR):
        return None, []

    run_folders = sorted(
        [f for f in glob.glob(os.path.join(RESULTS_DIR, '*')) if os.path.isdir(f)]
    )

    if not run_folders:
        return None, []

    latest_path = run_folders[-1]
    latest_folder = os.path.basename(latest_path)

    images = sorted([
        os.path.basename(f) for f in glob.glob(os.path.join(latest_path, '*'))
        if f.lower().endswith(('.png', '.jpg', '.jpeg'))
    ])

    return latest_folder, images


@medicine_bp.route('/dashboard', methods=['GET'])
def dashboard():
    latest_folder, images = get_latest_results()
    return render_template('dashboard.html', run_folder=latest_folder, images=images)


@medicine_bp.route('/dashboard/image/<path:filename>')
def dashboard_image(filename):
    latest_folder, _ = get_latest_results()
    if not latest_folder:
        return '', 404
    return send_from_directory(os.path.join(RESULTS_DIR, latest_folder), filename)
